### ISSUE TITLE
Control of the styles of the chevrons

### ISSUE THREAD

**Issue by SciManJD** [geekhybrid/vue3-tree-vue#10]
I would like to set different colors on the chevrons in the tree for each node, depending on a special condition. Is there an easy way to do this?

**Comment by geekhybrid** [comment]
Chevrons ? Expanded and collapse to have a different colour ?

**Comment by SciManJD** [comment]
Not different colors between the expanded and collapsed chevrons, but different colors between the chevrons in front of the different nodes. Something like this:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/qM2nj8c/tree.png" alt="tree" border="0"></a>

**Comment by geekhybrid** [comment]
@SciManJD 

Thanks for attaching this, and apologies for the delayed response.

A couple of observations:
1. From the image, it is not exactly clear if the colored boxes are checkboxes or expanders used to expand and or collapse the node.

2. If they are checkboxes, does it mean the checkboxes only apply to certain levels and not others? 

I assume it is possible to support custom expander elements. In this case, it could be these colored boxes that can be styled in whatever way you deem fit. 

If this assumption is validated, I think I can work to support something like

```html
<template>    
    <vue3-tree-vue :items="items" 
                   :isCheckable="false"
                   :hideGuideLines="false"
                   v-model:selectedItem="selectedItem">
       <template v-slot:item-prepend-expander="treeViewItem" >
             <your-component-here-with-styling  />
       </template>
    </vue3-tree-vue>
</template>
```

Regards,

**Comment by SciManJD** [comment]
Yes, this is exactly what I need. These are not check-boxes, but expanders. I want to control their color, depending on some internal states. I will be quite good if this feature can be supported.

**Comment by geekhybrid** [comment]
@SciManJD you can upgrade to 1.0.18 to customize your expander.
