### ISSUE TITLE
Async child load

### ISSUE THREAD

**Issue by Mawriks** [geekhybrid/vue3-tree-vue#12]
Hey, is this branch is alive?

Is this plugin has async load of child elements?
How I can made it?

**Comment by geekhybrid** [comment]
Hi,

If I understand correctly you will like to lazyload the treeview ?

**Comment by Mawriks** [comment]
yes! Correct
Is it real?

**Comment by geekhybrid** [comment]
This is currently not supported but will be in the next version coming up in a few weeks.

**Comment by Mawriks** [comment]
Nice. Thanks.
