### ISSUE TITLE
items are renderd as simple list but not as tree view

### ISSUE THREAD

**Issue by mhoelzner** [geekhybrid/vue3-tree-vue#13]
I am using vite with vue3 and created a component to show the treeview, i am fairly new to vue at this point and i do not understand why its not renderd at least a bit like a treeview.

"@vitejs/plugin-vue": "^4.2.3",
"vite": "^4.4.5"

```
<script setup>

// vue
import { ref } from 'vue'

// libraries
import Vue3TreeVue from 'vue3-tree-vue'

const items = ref([
    {
      "name": "Rejection Emails",
      "id": 1,
      "type": "emails",
      "children": [
        {
          "name": "Rejection Email 1",
          "id": 11,
          "type": "emails",
          "children": []
        }, 
        {
          "name": "Rejection Email 2",
          "id": 12,
          "type": "emails",
          "children": []
        }
      ]
    }
]);

</script>

<template>
  
  <div class="bg-[#e6e6e6] decoration-[#30373a] h-full">
    <!-- Default makes items selectable (one at a time) -->
    <vue3-tree-vue :items="items" 
                   :isCheckable="true"
                   :hideGuideLines="false">
      <!-- Applying some simple styling to tree-items -->
       <!-- <template v-slot:item-prepend-icon="treeViewItem" >
              <img src="./assets/folder.svg"
                   alt="folder"
                   v-if="treeViewItem.type === 'folder'"
                   height="20" width="20" />
       </template> -->
    </vue3-tree-vue>
  </div>

</template>

<style scoped>

</style>
```

if i leave it like that i will get 3 items with the checkbox in front of them under each other, no guidlines, no indentation; no arrow for opening or closing the root item;

i appreciate any help.

**Comment by geekhybrid** [comment]
Hello,

New to Vue ? You sure will love the View. 😅

Now to serious issues.

My guess is that you probably need to import the style sheet ?

You can import this into your main.[js/ts]

Or simply import it into your component.

**import 'vue3-tree-vue/dist/style.css';**

Let me know how that goes 😊

**Comment by mhoelzner** [comment]
Hello again, 

Thank you for replying so fast. 
That was it, so simple, yet so "hidden" 😅
As suggestion, could you include the two import command in the ReadMe, for newbies like me sure a benefit.
