### ISSUE TITLE
hideGuideLines="true" it seems don't working

### ISSUE THREAD

**Issue by clabnet** [geekhybrid/vue3-tree-vue#17]
Setting :hideGuideLines="true" or "false" it seems not make any difference.

**Comment by geekhybrid** [comment]
Updates are available in 2.0.4. Thanks

**Comment by geekhybrid** [comment]
<img width="514" alt="image" src="https://github.com/geekhybrid/vue3-tree-vue/assets/39003759/c1136dae-e15b-47da-a024-fa5bc5d22eb0">

Fixed. Will be available in the next update (2.0.4)
