### ISSUE TITLE
Feature Request: Prop to disable drag/drop

### ISSUE THREAD

**Issue by mrorabau** [geekhybrid/vue3-tree-vue#24]
It is easy to make it not do anything when you drag/drop the order, however it might be better to disable it completely so the user doesn't think something is wrong with the interface.

**Comment by ajmcgrail** [comment]
I'm surprised this hasn't been closed- the only thing you need to do is to set the \@dropValidator function to undefined as far as I can tell. Am I missing something, or was this just implemented after this issue was made?

**Comment by geekhybrid** [comment]
AFAIK, the drag/drop feature existed prior to this issue. I will look into this over the weekend. @ajmcgrail

**Comment by geekhybrid** [comment]
Fix now available in 2.0.11.

My understanding of this issue is that we do not even want to show the drag-and-drop effect if it is disabled.
To achieve this DO NOT set the `onDropValidator`, or you may set it to undefined.
