### ISSUE TITLE
Line Styling

### ISSUE THREAD

**Issue by berge472** [geekhybrid/vue3-tree-vue#27]
It looks like all of the changes to terminate line endings were removed in commit e75a80aa. Was this intentional?

**Comment by geekhybrid** [comment]
Yes I vaguely remember a set of core issues that were strangely related to those changes. I had to quickly back them out.

I feel this project is in dire need of component tests so we can add features with confidence.

**Comment by berge472** [comment]
If you let me know what the issues were I can take a look at them. 

I would like to add a context menu slot, but right now my app is rolled back to 2.0.6

**Comment by geekhybrid** [comment]
Hi,

Sure. Thanks for offering to fix them. I will revert to that state of the code and test the features and let you know. Apologies for the inconvenience.
