### ISSUE TITLE
How to expand all nodes without knowing the types

### ISSUE THREAD

**Issue by SciManJD** [geekhybrid/vue3-tree-vue#3]
Is there an easy way to expand all nodes in the tree without knowing the types? My problem is the following. I read the tree structure from the server, but the types are not know in the WEB application. I don't want to fix them, because new types can appear later and this will lead to update of the WEB application. I tried the following workaround, but I don't like it, therefore I'm searching a better solution. In the lifetime hook "created" I read the tree structure (needs to be blocking), then I search all the types that are received, I create dynamically the array that is given to the property "expandedTypes" and set the property "items". This works, but I want to avoid this blocking read. I tried to make it asynchronous (with fetch), but then I had different problems. It seems that I set "items" before "expandedTypes", the expansion is not applied. Also if I do the correct sequence, but on "mounted", the also the expansion is not made. What is the right way to do this?

**Comment by geekhybrid** [comment]
Hi @SciManJD  can you provide a code snippet of your use case ?

Please let it contain the code for the blocking read.

**Comment by SciManJD** [comment]
I use the lifecycle hook "created". The template and the code are the following:
`
<template>
    <vue3-tree-vue  
        :items="items"
        :isCheckable="false"
        :hideGuideLines="false" 
        :expandedTypes="allTypes" 
        v-model:selectedItem="selectedItem"  
        @onSelect="getSelectedItem">
        <template v-slot:item-prepend-icon="treeViewItem" >
            <div v-for="(types, itemClass) in deviceData" v-bind:key="itemClass.id">
                <img :src="getImgUrl(itemClass)" class="item-icon" 
                    v-if="showIcon(treeViewItem.type, itemClass)">
            </div>
        </template>
        <template v-slot:item-prepend>
            <div style="width: 10px;"/>
        </template>
    </vue3-tree-vue>
</template>

<script>
    import Vue3TreeVue from 'vue3-tree-vue';
    import '@/assets/css/tree-style.css';
    export default {
       ...
        data() {
            return {
                items: [],
                selectedItem: 1,
                allTypes: [],
                compReadyEvent: false
            }
        },
        created() {
            // Get the device tree structure
            var xhttp = new XMLHttpRequest();
            xhttp.overrideMimeType("application/json");
            xhttp.open("POST", "get_dev_tree/", false);
            xhttp.send();
            var response = JSON.parse(xhttp.responseText);

            // Function that parses the JSON response and finds all item types
            const getPropValues = (obj, prop) => 
                (res => (JSON.stringify(obj, (key, value) => 
                    (key === prop && res.push(value), value)), res))([]);

            // Find all item types and load then to the variable that is used for selection of the opened items in the tree
            this.allTypes = getPropValues(response, "type");
            // Get the divice tree and show it
            this.getDeviceTree();
           ...
        },
`

If I set the property "expandedTypes" later when the tree is already shown, it doesn't expand the nodes.

**Comment by geekhybrid** [comment]
@SciManJD,

To expand all nodes by default, please set the `expandAll` props to `true`.

Available on >= 1.0.14.
