### ISSUE TITLE
How to manually set selected item?

### ISSUE THREAD

**Issue by Mawriks** [geekhybrid/vue3-tree-vue#31]
I try to use v-model:selectedItem, but it no effect to component

**Comment by geekhybrid** [comment]
Hi @Mawriks, not sure you can use a prop like that.

To manually set an item as selected you may,
```
export interface TreeViewItem {
...
  checked?: boolean; // You can set this. Each item in the `items` array can set this.
...
}
```

**Comment by Mawriks** [comment]
> Hi @Mawriks, not sure you can use a prop like that.
> 
> To manually set an item as selected you may,
> 
> ```
> export interface TreeViewItem {
> ...
>   checked?: boolean; // You can set this. Each item in the `items` array can set this.
> ...
> }
> ```

I did like that. I use this component to change router when I click on element from list.
Now I need to show modal before update router and this component creates own local items that change selected item .
I need to prevent selection before router change. It's needed for prevent highlighting of clicked element. Maybe you have some idea in this case?

**Comment by geekhybrid** [comment]
Do you have a small code sample to reproduce this ?

**Comment by Mawriks** [comment]
> Do you have a small code sample to reproduce this ?

Hey! I did a sandbox. 
what need to do to reproduce:
1) set new val to input
2) choose new item from list
3) decline btn in modal
what i want to do:
if no router update -> no select clicked item
if router changed -> show new selected item in list
https://codesandbox.io/p/devbox/xpwtz4

**Comment by geekhybrid** [comment]
@Mawriks 

Thanks for providing the Sandbox, nice and neat.

I think this is a control use case your app needs to handle and not the treeview component. I will suggest you do something like this if you want a loosely coupled way of interacting between the components on the sandbox.

![image](https://github.com/user-attachments/assets/ff3d9471-9222-4c91-8901-45f165a9d528)

**Comment by Mawriks** [comment]
> @Mawriks
> 
> Thanks for providing the Sandbox, nice and neat.
> 
> I think this is a control use case your app needs to handle and not the treeview component. I will suggest you do something like this if you want a loosely coupled way of interacting between the components on the sandbox.
> 
> ![image](https://private-user-images.githubusercontent.com/39003759/361823213-ff3d9471-9222-4c91-8901-45f165a9d528.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MTIyNTEsIm5iZiI6MTcyNTgxMTk1MSwicGF0aCI6Ii8zOTAwMzc1OS8zNjE4MjMyMTMtZmYzZDk0NzEtOTIyMi00YzkxLTg5MDEtNDVmMTY1YTlkNTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDE2MTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YjU0MzdhZWY0YjgyMTA5NjhlNGU4YTM1NDUzZjc0ODljYTJlNWFjOGZkYWNhNjNjZWJiZGZjMzcxMjFmNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VqOi57emOCj2cNMWxtTpFZxv9L4z2OAoJMnuz2CzFrQ)

Hey! I did it by saving current item and next item. But I got a trouble with selected item. When I choose next item -> it highlighting. I think that it's ok for now. Thanks alot.
