### ISSUE TITLE
Selected item style

### ISSUE THREAD

**Issue by determaer** [geekhybrid/vue3-tree-vue#34]
how i able to use class selected-tree-item? if i append this like in the snippet below, it doesn't work

```htm
<vue3-tree-vue
  :items="files"
>    
</vue3-tree-vue>

<style scoped>
.selected-tree-item{
  ...
}
</style>
```

**Comment by geekhybrid** [comment]
@determaer 
Can you remove the `scoped` style? 
And target `.tree-item.selected-tree-item`?

**Comment by determaer** [comment]
that's worked, thanks!
