### ISSUE TITLE
Changing the style of the list items

### ISSUE THREAD

**Issue by SciManJD** [geekhybrid/vue3-tree-vue#4]
I want to change the styles of the list elements to change the view of the tree. I made this successfully for the tree using directly the following settings in style.css file:

```
li {
   ...
}
li:last-child {
   ...
}
li:before {
   ...
}
li:last-child:before {
  ...
}
```

Everything works fine when I compile the tree outside of my project. But when I integrate it in my project, these styles are applied globally and change many other elements. I tried to copy the styled directly in my <style scoped></style> section when I import and use this tree component, but then the syles are not applied in the tree,
I suppose that there are some classes that are use for the "li" and "ul" elements and that I can modify. I made some trials, but without success. Can you tell me the name of the classes that I can use?

**Comment by geekhybrid** [comment]
In v1.0.15, you can use the "tree-item-node" to style the `li` and "tree-items-node-parent" to style the `ul`.
