### ISSUE TITLE
How to select an item via the code

### ISSUE THREAD

**Issue by SciManJD** [geekhybrid/vue3-tree-vue#5]
I need to select a specific item in the tree when I create the tree for a first time. How can I do this? If I set a value to selectedItem, the selection is not made.

**Comment by geekhybrid** [comment]
Can you share some simple snippets on how you are attempting to do this?

Also bear in mind;

1. Selection is highlighting an item not "checking" it with a checkbox.
2. You can select only one item at a time, by clicking it.
3. When you pass an object into the `SelectedItem` prop, you have to set the `isCheckable` prop to false. This will turn off checkbox selection and use click-selection.

**Comment by SciManJD** [comment]
Thank you for the advice, but I found my problem. I'm passing only the id to SelectedItem. When I pass the complete object, it works fine.
