### ISSUE TITLE
Generating event by click second time on the same item

### ISSUE THREAD

**Issue by SciManJD** [geekhybrid/vue3-tree-vue#7]
Hi!
I need to get onSelect event on every selection of an item, even if the item is already selected. But there is no event if the item is selected. Is there a way to do this?

**Comment by geekhybrid** [comment]
Hi,

I don't think so, perhaps I can expose an **onlick**.

I am not sure how I feel about firing the selected event twice when the element was already selected. What do you think ?

**Comment by SciManJD** [comment]
My problem is the following. In my application, the user navigates by clicking on the tree items to different views. That works fine, but there is also a drop-down menu, that can open some views, let's say with some settings for example. If  the user open such view from the drop-down menu, then he wants to return back to the last view, selected by clicking on a tree item, nothing happens.

**Comment by geekhybrid** [comment]
Thanks for the details @SciManJD 

I don't think it is a bad idea to still fire the event `onSelect`, for a node that is already selected.
I just patched it.

You can update to the latest version [1.0.17](https://www.npmjs.com/package/vue3-tree-vue/v/1.0.17). Enjoy! 
Please feel free to close this issue when you confirm it addresses your use case.

**Comment by SciManJD** [comment]
All works just fine. Thanks!

**Comment by SciManJD** [comment]
Fixed!
