### ISSUE TITLE
请问，如何import进来

### ISSUE THREAD

**Issue by liu3104009029** [geekhybrid/vue3-tree-vue#8]
如题

**Comment by geekhybrid** [comment]
Hi, could you please leave your comments in english ?

你好，你能用英文發表評論嗎？

**Comment by liu3104009029** [comment]
how to import in vue page

**Comment by liu3104009029** [comment]
when i use in vue3 project, get the error:
The following dependencies are imported but could not be resolved:
  vue3-tree-vue/dist/types/src/types

And my code is:
import Vue3TreeVue from 'vue3-tree-vue'
import { TreeViewItem } from 'vue3-tree-vue/dist/types/src/types'

**Comment by geekhybrid** [comment]
Oops!

@liu3104009029 have you been able to resolve this? Also what version are you working with? Thanks.

**Comment by liu3104009029** [comment]
still not resolved！
vue3-tree-vue@1.0.17

**Comment by geekhybrid** [comment]
Thanks for the update. Kindly provide a sample I can reproduce ?

**Comment by liu3104009029** [comment]
It may be that other unknown packages are referenced in my project, causing this error. I apologize for my sloppiness, sorry! ! !
